AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Name: "BatchApi"
    Cors: 
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:

  BatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 15
      MemorySize: 512
      CodeUri: ../src/batch
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue BatchTableName
      Environment:
        Variables:
          TABLE_NAME: !ImportValue BatchTableName
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /batches/{batch_id}
            Method: GET
        PostApi:
          Type: Api
          Properties:
            Path: /batches
            Method: POST
