AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Name: "ParticipantApi"
    Cors: 
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:

  PostParticipantFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: participant.handler
      Runtime: nodejs12.x
      Timeout: 15
      MemorySize: 512
      CodeUri: ../src/participant
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue ParticipantTableName
      Environment:
        Variables:
          TABLE_NAME: !ImportValue ParticipantTableName
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /participants/{session_id}
            Method: GET
        PostApi:
          Type: Api
          Properties:
            Path: /participants
            Method: POST
