AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  ResultTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: batch_id
          AttributeType: S
        - 
          AttributeName: session_id
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: session_id
          KeyType: HASH
        - 
          AttributeName: batch_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: Result

Outputs:
  ResultTableName:
    Description: Result table name
    Value: !Ref ResultTable
    Export:
      Name: ResultTableName